version: '3.7'

services:
  mysql:
    build:
      context: ./mysqldocker
    container_name: mysql
    volumes:
      - ./db-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  app:
    build:
      context: ./docker
    container_name: app
    depends_on:
      - mysql
    volumes:
      - .:/app:cached
    ports: 
      - "80:80"
