version: '3.4'

services:
  app:
    image: php:8.0-rc-fpm
    container_name: app
    depends_on:
      - web
      - mysql
    #      - keycloak
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html

  web:
    build:
      context: ./docker/caddy
    ports:
      - 80:80
      - 443:443

  mysql:
    image: jhmachado12/mysql:8
    container_name: mysql
    volumes:
      - ./db-data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret

  keycloak:
    image: quay.io/keycloak/keycloak:11.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloack
      DB_USER: root
      DB_PASSWORD: secret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    depends_on:
      - mysql

